# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MapMatcherPlugin
                                 A QGIS plugin
 MapMatcherPlugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-07-09
        copyright            : (C) 2022 by ENSG
        email                : mdvd@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Marie-Dominique Van Damme'
__date__ = '2022-07-09'
__copyright__ = '(C) 2022 by ENSG'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingParameterCrs,
                       QgsRunProcess
                       )


class MapMatchingAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        
        print ('11')
        
#        self.addParameter(
#            QgsProcessingParameterFeatureSource(
#                'gpxLayer',
#                self.tr('GPS Layer'),
#                [QgsProcessing.TypeVectorPoint]
#            )
#        )
#            
        self.addParameter(
            QgsProcessingParameterCrs(
                'projection',
                self.tr('Projection des points gps en sortie')
                )
        )
            
#        self.addParameter(
#            QgsProcessingParameterEnum(
#                'attributs',
#                self.tr("Select options"),
#                options=['cpt', 'EPSG:215 - RGF93'],
#                allowMultiple=True
#            )
#        )
            
#        self.addParameter(
#            QgsProcessingParameterFileDestination (
#                'csvchemin',
#                self.tr('Fichier csv'),
#                defaultValue = '/home/marie-dominique/test.csv',
#                optional = False
#            )
#        )
            
#        self.addParameter(
#            QgsProcessingParameterFeatureSink(
#                    'csvLayer',
#                    self.tr("Fichier csv"),
#                    QgsProcessing.TypeVectorLine, 
#                    '',
#                    optional = False
#            )
#        )


    def buildCommandLine(self):
        
        jarName = 'mapmatcher-1.5-jar-with-dependencies.jar'
        
        cmds = []
        cmds.append("java")
        cmds.append("-jar")
        cmds.append('/home/marie-dominique/CHOUCAS/MAPMATCHER/' + jarName)
        cmds.append('/home/marie-dominique/CHOUCAS/MAPMATCHER/parameters.txt')
        
        cmd = " ".join(cmds)
        return cmd
        

    def processAlgorithm(self, parameters, context, feedback):
        """
        """
        
        myRun = self.buildCommandLine()
        #process = QgsRunProcess(self.iface)
        #process.start(cmd)
        #process.waitForFinished(3000)
        #process.kill()
        
        QgsRunProcess.create(myRun, True)

#        pathcsv = parameters['csvchemin']
#        f = open(pathcsv, 'w')
#        writer = csv.writer(f)
#        # writer.writerow(['id','x', 'y', 'z', 'no_time_stamp'])
#        
#        crsSrc = QgsCoordinateReferenceSystem(4326)    # WGS 84
#        crsDest = self.parameterAsCrs(parameters, 'projection', context)
#        #crsDest = QgsCoordinateReferenceSystem(2154)  # Lambert93
#        xform = QgsCoordinateTransform(crsSrc, crsDest, QgsProject.instance())
#        
#        gpsLayer = self.parameterAsSource(parameters, 'gpxLayer', context)
#        total = 100.0 / gpsLayer.featureCount() if gpsLayer.featureCount() else 0
#        features = gpsLayer.getFeatures()
#        for current, feature in enumerate(features):
#            # Stop the algorithm if cancel button has been clicked
#            if feedback.isCanceled():
#                break
#            
#            gPoint = feature.geometry()
#            gPoint.transform(xform)
#            
#            attrs = feature.attributes()
#            writer.writerow([attrs[2], gPoint.asPoint().x(), gPoint.asPoint().y(), attrs[3], 'no_time_stamp'])
#
#            feedback.setProgress(int(current * total))
#            
#        f.close()
            
        return {'retour': 'OK'}
    
    

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Map matching d'une trace"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2-Processing'

    def tr(self, string):
        return QCoreApplication.translate('2-Processing', string)

    def createInstance(self):
        return MapMatchingAlgorithm()

